# Enable Iceberg SQL extensions for Spark
spark.sql.extensions    org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions


# Register a catalog named "dev_catalog" using the REST implementation
# This catalog name is local to Spark and does not need to match the catalog name in Polaris
spark.sql.catalog.dev_catalog                                     org.apache.iceberg.spark.SparkCatalog

spark.sql.catalog.dev_catalog.type                                rest
spark.sql.catalog.dev_catalog.uri                                 http://polaris:8181/api/catalog
spark.sql.catalog.dev_catalog.warehouse                           ecom-lakehouse

spark.sql.catalog.dev_catalog.header.Polaris-Realm                polaris

spark.sql.catalog.dev_catalog.oauth2-server-uri                   http://polaris:8181/api/catalog/v1/oauth/tokens
spark.sql.catalog.dev_catalog.credential                          44d4ec3975af1142:977682db5671bb39040b29fda9ca0936
spark.sql.catalog.dev_catalog.scope                               PRINCIPAL_ROLE:ALL

spark.sql.catalog.dev_catalog.s3.endpoint             http://minio:9000
spark.sql.catalog.dev_catalog.s3.access-key-id        minio
spark.sql.catalog.dev_catalog.s3.secret-access-key    minioadmin
spark.sql.catalog.dev_catalog.s3.path-style-access    true
spark.sql.catalog.dev_catalog.client.region           us-east-1


# S3 setting (if you want to read directly S3 without using catalog)
spark.hadoop.fs.s3a.endpoint                    http://minio:9000
spark.hadoop.fs.s3a.access.key                  minio
spark.hadoop.fs.s3a.secret.key                  minioadmin
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.connection.ssl.enabled      false
spark.hadoop.fs.s3a.endpoint.region             us-east-1
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem


# Use 'dev_catalog' catalog as default
spark.sql.defaultCatalog    dev_catalog
