# The name of the file is used as the catalog name only in Trino.
# It can be different from the catalog name defined in Polaris.


# https://trino.io/docs/current/object-storage/metastores.html#rest-catalog
connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.warehouse=ecom-lakehouse

iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
iceberg.rest-catalog.oauth2.credential=44d4ec3975af1142:977682db5671bb39040b29fda9ca0936
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL


# https://trino.io/docs/current/object-storage/file-system-s3.html
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.aws-access-key=minio
s3.aws-secret-key=minioadmin
s3.path-style-access=true
s3.region=us-east-1
